services:
    db:
        image: postgis/postgis:15-3.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: jpksj
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    jpksj-to-sql:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./tmp:/app/tmp
        environment:
            - DATABASE_URL=host=db user=postgres password=postgres dbname=jpksj
        command: jpksj-to-sql "host=db user=postgres password=postgres dbname=jpksj"
        restart: on-failure

volumes:
    postgres-data:
